apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  name: cryptocurrency-services-api-gateway
  name: {{ .Release.Name }}-ingress
  annotations:
#    kubernetes.io/ingress.global-static-ip-name: masternodes-online-supplement-ip
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}-static-ip
  labels:
    app: {{ .Release.Name }}
spec:
  backend:
    serviceName: {{ .Release.Name }}-service
    servicePort: 8080

