apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  name: cryptocurrency-services-api-gateway
  name: {{ template "fullname" . }}-ingress
  annotations:
#    kubernetes.io/ingress.global-static-ip-name: masternodes-online-supplement-ip
    kubernetes.io/ingress.global-static-ip-name: {{ template "fullname" . }}-static-ip
  labels:
    app: {{ template "fullname" . }}
spec:
  backend:
    serviceName: {{ template "fullname" . }}-service
    servicePort: 8080

