apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

    app: {{ template "fullname" . }}
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod,swagger"

        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            secretKeyRef:
              name: jenkins-secrets
              key: eureka-client-service-url-defaultzone

        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            secretKeyRef:
              name: jenkins-secrets
              key: spring-cloud-config-uri

        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: jenkins-secrets
              key: spring-data-mongodb-uri

        - name: SPRING_DATA_MONGODB_DATABASE
          value: "{{ .Values.database }}"

        - name: JHIPSTER_SLEEP
          value: "30"

        - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
          value: "elastisearch-service:9300"

        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
