apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: jenkins-pod-preset-master
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [jenkins]}
  env:
    - name: MONGO_PROD_TEST_USER
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mongo-prod-test-user
    - name: MONGO_PROD_TEST_PASS
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mongo-prod-test-pass

