apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: jenkins-pod-preset-slave
spec:
  selector:
    matchExpressions:
      - {key: jenkins, operator: In, values: [slave]}
  env:
    - name: MONGO_PROD_TEST_USER_PASS
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mongo-prod-test-user-pass
