apiVersion: v1
kind: PodPreset
metadata:
  name: jenkins-pod-preset-master
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [jenkins]}
  env:
    - name: MONGO_PROD_TEST_USER_PASS
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mongo-prod-test-user-pass

