apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
type: Opaque
data:
  mongo-prod-test-user: "X_MONGO_PROD_TEST_USER_X"
  mongo-prod-test-pass: "X_MONGO_PROD_TEST_PASS_X"
  spring-data-mongodb-uri: "X_SPRING_DATA_MONGODB_URI_X"
